/*--------------------------------------Airport-Airline (Many-to-Many Relation)--------------------------*/

CREATE TABLE Airports-Airline (

    Airline_code VARCHAR(100) NOT NULL,
    AirportCode VARCHAR(5) NOT NULL,



    FOREIGN KEY (Airline_code) REFERENCES Airline(Code),
    FOREIGN KEY (AirportCode) REFERENCES Airports(airport_code)


);

INSERT INTO Airports-Airline (Country,Airline) VALUES
('India','AIRI'),
('Sri Lanka', 'AIRI')
('Australia', 'AIRI')
('Austria', 'AIRI')
('Bahrain', 'AIRI')
('Bangladesh', 'AIRI')
('Canada', 'AIRI')
('Denmark', 'AIRI')
('France', 'AIRI')
('Germany', 'AIRI')
('Hong Kong', 'AIRI')
('Israel', 'AIRI')
('Italy', 'AIRI')
('Japan', 'AIRI')
('Malaysia', 'AIRI')
('Netherlands', 'AIRI')
('Russia', 'AIRI')
('Saudi Arabia', 'AIRI')
('South Korea', 'AIRI')
('Switzerland', 'AIRI')
('Thailand', 'AIRI')
('United Kingdom', 'AIRI')
('United States', 'AIRI')

('India','VIST')

('India','LUFT')
('Sri Lanka','LUFT')
('United States','LUFT')
('Thailand','LUFT')
('Iran','LUFT')
('Iraq','LUFT')
('Israel','LUFT')
('China','LUFT')
('Hong Kong','LUFT')
('Canada','LUFT')
('South Africa','LUFT')
('Singapore','LUFT')
('Vietnam','LUFT')
('United Arab Emirates','LUFT')

('India','EITH')
('Australia','EITH')
('Hong Kong','EITH')
('Indonesia','EITH')
('Japan','EITH')
('Malaysia','EITH')
('Pakistan','EITH')
('Singapore','EITH')
('Saudi Arabia','EITH')
('South Africa','EITH')
('South Korea','EITH')
('Sri Lanka','EITH')
('United Arab Emirates','EITH')
('Vietnam','EITH')
('New Zealand','EITH')
('China','EITH')
('Egypt','EITH')

('India','EMI')
('South Africa','EMI')
('Australia','EMI')
('Malaysia','EMI')
('Taiwan','EMI')
('Indonesia','EMI')
('China','EMI')
('Japan','EMI')
('New Zealand','EMI')
('Singapore','EMI')
('Vietnam','EMI')
('Denmark','EMI')
('Russia','EMI')
('Netherlands','EMI')
('France','EMI')
('Spain','EMI')
('United Kingdom','EMI')
('Germany','EMI')
('Italy','EMI')
('Swedan','EMI')
('Swizerland','EMI')
('United States','EMI')
('Canada','EMI')
('Brazil','EMI')
('Iraq','EMI')
('Israel','EMI')
('Iran','EMI')
('United Arab Emirates','EMI')

('India','IDIG')

('India','SPCJ')
('Saudi Arabia','SPCJ')
('Italy','SPCJ')
('Thailand','SPCJ')
('Sri Lanka','SPCJ')
('United Arab Emirates','SPCJ')

('India','QTRA')
('Spain','QTRA')
('United States','QTRA')
('Malaysia','QTRA')
('Australia','QTRA')
('China','QTRA')
('France','QTRA')
('Germany','QTRA')
('Indonesia','QTRA')
('Iran','QTRA')
('Iraq','QTRA')
('Italy','QTRA')
('Japan','QTRA')
('Netherlands','QTRA')
('Pakistan','QTRA')
('Singapore','QTRA')
('South Korea','QTRA')
('Swedan','QTRA')
('United Kingdom','QTRA')
('Vietnam','QTRA')
('Austria','QTRA')
('Denmark','QTRA')
('Egypt','QTRA')
('Germany','QTRA')
('New Zealand','QTRA')
('Pakistan','QTRA')
('Philipines','QTRA')
('Russia','QTRA')
('Saudi Arabia','QTRA')
('South Africa','QTRA')
('Sri Lanka','QTRA')
('Thailand','QTRA')
('United Arab Emirates','QTRA')
('Brazil','QTRA')
('Qatar ','QTRA');



